### PR TITLE
Mnemonics: Add Explanation Page

### LINKED ISSUE #70: Add `MnemonicsExplanationPage`
1) Fork [PlutoWallet](https://github.com/RostislavLitovkin/PlutoWallet) repo
2) Switch to `devel` branch
3) Create a new branch called **MnemonicsExplanationPage**
4) In `PlutoWallet/Components/Mnemonics/` folder, create a new **ContentPage** and name it `MnemonicsExplanationPage.xaml`
5) Use the following xaml code as template for the page:
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="PlutoWallet.Components.Extrinsic.ExtrinsicDetailPage"
             xmlns:navigationbar="clr-namespace:PlutoWallet.Components.NavigationBar"
             xmlns:confirmtransaction="clr-namespace:PlutoWallet.Components.ConfirmTransaction"             Title="MnemonicsExplanationPage"
         BackgroundColor="Black">
    <AbsoluteLayout AbsoluteLayout.LayoutBounds="0.5, 0.5, 1, 1" AbsoluteLayout.LayoutFlags="All">

        <Image AbsoluteLayout.LayoutBounds="0.5, 0.5, 1, 1" AbsoluteLayout.LayoutFlags="All"
           Source="{AppThemeBinding Light=whitebackground.png, Dark=darkbackground2.png}"
           Opacity="{AppThemeBinding Light=0.96}"
           Aspect="AspectFill"/>

        <ScrollView Orientation="Vertical"
                x:Name="scrollView"
                AbsoluteLayout.LayoutBounds="0.5, 0.5, 1, 1"
                AbsoluteLayout.LayoutFlags="All"
                Padding="0, 55, 0, 0">
            <!--
            Put content here
            -->

        </ScrollView>

        <navigationbar:TopNavigationBar Title="Title of the page"
                                    x:Name="topNavigationBar" />

        <confirmtransaction:ConfirmTransactionView />

    </AbsoluteLayout>

</ContentPage>
```
This will setup the correct background image, etc..

6) Add the following 2 lines to the constructor:
```
public MnemonicsExplanationPage()
{
    NavigationPage.SetHasNavigationBar(this, false);
    Shell.SetNavBarIsVisible(this, false);

    InitializeComponent();
}
```
7) Fill the content of the page. Be sure to use the custom `Card` element.
8) Add a button to `PlutoWallet/View/MnemonicsPage.xaml` which will navigate the user to the `MnemonicsExplanationPage`
9) Make PR

### PR DESCRIPTION
**Pull request by mittal-parth**
Adds a MnemonicsExplanationPage as per #70.

Adds the content as specified in the issue description along with a URL handler.

Also adds a button to navigate the user.

Closes #70

### CODE REVIEW

**Comment by RostislavLitovkin** [comment]
Thanks very much for your contribution!
I think you did a good job, I hope you had fun coding it. If you want something more challenging, you can consider trying this issue as well: https://github.com/RostislavLitovkin/PlutoWallet/issues/50.

I would be happy to reward you with 50$ equivalent in USDT/USDC/DOT for your contribution. Please, share me your Polkadot address, or you would like to keep the address anonymous, you can contact me on discord under the `rostadev` username.

**Comment by RostislavLitovkin** [comment]
quick feedback: The task said fork and merge into the `devel` branch. But it is fine.

**Comment by mittal-parth** [comment]
Hey @RostislavLitovkin, thanks!

Learnt something new, wasn't aware of Microsoft's cross platform framework.

> quick feedback: The task said fork and merge into the devel branch. But it is fine.

My bad. I did branch out from 'devel' but kept the target branch wrong.

Here is my polkadot address: 5GsLutpKjbzsbTphebs9Uy4YK6gTN47MAaz6njPktidjR5cp

Thanks again!

**Comment by RostislavLitovkin** [comment]
Alright, the reward has been sent: https://assethub-polkadot.subscan.io/tx/0x166597b7b4d757116e609d346508834426fcecaae8ea993b048d9f95594e0fed

**Pull request merged**
